name: Development workflow

on:
  push:
    branches:
    - Development

jobs:
  base-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist
          # exit-zero treats all errors as warnings
          flake8 . --count --max-line-length=80 --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install pyright
        run: npm install pyright -g
      - name: Run pyright
        run: pyright SQLMatches/*
      - name: MySQL server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ secrets.DATABASE_DB }}
          mysql user: ${{ secrets.DATABASE_USER }}
          mysql password: ${{ secrets.DATABASE_PASS }}
          host port: 3800
          container port: 3800
      - name: Wait for MySQL to startup
        run: sleep 15
      - name: Run unit tests
        run: python run_tests.py --root_steam_id ${{ secrets.ROOT_STEAM_ID }} --db_username ${{ secrets.DATABASE_USER }} --db_password ${{ secrets.DATABASE_PASS }} --db_server 127.0.0.1 --db_port 3800 --db_database ${{ secrets.DATABASE_DB }}
